---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development

# make sure namespace exists
resources:
  - namespace.yaml


helmCharts:
  - name: gitea
    repo: https://dl.gitea.io/charts/
    version: 1.18.3
    #includeCRDs: true # just for first installation. needs to be commented out afterwards
    releaseName: gitea
    namespace: development
    valuesFile: values.yaml
