---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph

# make sure namespace exists
resources:
  - namespace.yaml

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: 1.10.10
    includeCRDs: true
    releaseName: rook
    namespace: rook-ceph
    valuesFile: operator-values.yaml
