---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

# make sure namespace exists
resources:
  - namespace.yaml
  # - https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
  # - environment.yaml
  - issuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.11.0
    includeCRDs: true
    releaseName: cm
    namespace: cert-manager
    valuesFile: values.yaml

generators:
  - secret-generator.yaml
