---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi

resources:
  - namespace.yaml
  - driver-config-secret.yaml

helmCharts:
  - name: democratic-csi
    releaseName: democratic-csi
    namespace: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    version: 0.13.5
    valuesFile: values.yaml

#generators:
#  - secret-gen.yaml
