apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: db-secrets
data:
    username: ENC[AES256_GCM,data:CABIoOHTTD4=,iv:Ut2p1ONGOKo6chKofmBAQ9gDli+j/RXlbXU0wYXefhc=,tag:UMyPDkwZNi0n2w08cwCZkQ==,type:str]
    password: ENC[AES256_GCM,data:Wf5gkSTv1DcaBb+UsbNwsCUTZemHwLK32I0M5cKw99CG7VGKQPoRoA==,iv:yvg3cq0baeVKpzkdu80uOm3DBqOGP/tZgbrrg1aBolA=,tag:inyYEoCWwdtu4nb1/+Ewpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tv5ru9rqj3s42gcc8hjtd2qcrtlxcdah5zw3ztzhy5dchc0f33aqwu86dz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiN2RhUTgvL081cFdRdzVT
            NFZ5TjRkSCtmK3pZM0lZdFhCblcvUTJseGpZCnEvdkFJMTdiUEI3UGxDcEhSM3lj
            Y0ppVmN3alBYdVRVNjlrL2ZDSW1yU2sKLS0tIElLQkZOVWUrbHA3ZTJTRElESXl6
            cDFXN1M0ZzRMZXlIQk53RjA4VFhnbXMKXsD67Btflh/UH2mRJDp4/T3a3W4I4C+8
            PIz+6wz9WTQPyVUeDUb8JFYPZZlND8nNmsWMzJtdecq5mDXXz3WNIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T02:28:51Z"
    mac: ENC[AES256_GCM,data:hlYdCUoRZrRa4HNwMbp/Tp3YB20ttqurZcRKBFLXWVJaE8QmYlvk98vLyQSVuvXvuryJWUFXFsXqzWrxALy2oIT7UD2ePPRyI2ffJQmQyHLwjjwNYST0m60eTP2lursI0niHd6AkwCouVfJ6gfSvHFPF/Mxn1moaEW2raoQTg/o=,iv:Ft+VLMSYnwYniZEH2EfOAPP4ZZ7OwpYEpVa4hiBhsgg=,tag:8f1dpWm3a5RlNiPMn42IyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
