---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development

# make sure namespace exists
resources:
  - namespace.yaml
  - custom.yaml

generators:
  - secret-gen.yaml
