---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

# make sure namespace exists
resources:
  - namespace.yaml
  # - fix.yaml
  - ingress.yaml
  - prom-storage.yaml
#  - service.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 43.0.0
    includeCRDs: true # just for first installation. needs to be commented out afterwards
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml

generators:
  - ./sec-gen.yaml
